-- Superseded by the applied QA migration:
-- supabase/migrations/20261011012626_restrict_legacy_workspace_state_to_admins_qa.sql
-- Do not apply this draft separately. It is retained as a historical note only.
