-- Superseded duplicate filename. The applied Phase C6 migration is tracked as
-- 20261010000505_phase_c6_scope_case_linked_resource_policies.sql to match
-- Supabase migration history. This placeholder intentionally performs no SQL.
